# Generated by Django 3.0.2 on 2020-01-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='pub_date',
            new_name='show_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.FloatField(default='0', verbose_name='Price (RM)'),
        ),
        migrations.CreateModel(
            name='BookingMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.FloatField(verbose_name='Pax')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('email', models.CharField(max_length=200, verbose_name='Customer Email')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_name', to='booking.Movie')),
            ],
        ),
    ]
